# Generated by Django 5.1.7 on 2025-03-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис товару')),
                ('price', models.IntegerField(verbose_name='Ціна (в грн)')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='Ціна зі знижкою')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('available', models.BooleanField(default=True, verbose_name='Доступність товару')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул (SKU)')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('attributes', models.JSONField(blank=True, default=dict, null=True, verbose_name='Додаткові характеристики')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категорія')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'sku')},
            },
        ),
    ]
