# Generated by Django 5.1.7 on 2025-04-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay'), ('monopay', 'MonoPay'), ('google', 'Google Pay')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('paid', 'Оплачено'), ('failed', 'Помилка')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='ID транзакції від платіжної системи', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='products.order')),
            ],
        ),
    ]
